import type { ColumnType, Generated } from 'kysely';
import type { BigIntString, Timestamp } from './helpers.js';

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface AutocreatorData {
  is_ignore_autocreator: boolean;
  user_id: BigIntString;
}

export interface Channels {
  channel_id: BigIntString;
  channel_name: string;
  guild_id: BigIntString;
  guild_name: string;
}

export interface DbInfo {
  applied_at: Timestamp;
  initialize_at: Timestamp;
  last_sync_at: Timestamp;
  version: number;
}

export interface MessageMain {
  author_id: BigIntString;
  channel_id: BigIntString;
  created_at: Timestamp;
  guild_id: BigIntString;
  is_create_thread: boolean;
  is_deleted: boolean;
  is_update: boolean;
  message_id: BigIntString;
  message_jump_url: string;
  thread_id: BigIntString | null;
}

export interface PostMembers {
  first_join_at: Timestamp;
  is_leave: boolean;
  is_thread_owner: boolean;
  last_join_at: Timestamp;
  last_leave_at: Timestamp | null;
  last_message_at: Timestamp | null;
  last_message_id: BigIntString | null;
  message_count: Generated<number | null>;
  thread_id: BigIntString;
  user_id: BigIntString;
}

export interface PostsMain {
  attachment_urls: Json | null;
  author_id: BigIntString;
  channel_id: BigIntString;
  channel_name: string;
  content_tokenized: string | null;
  created_at: Timestamp;
  delete_at: Timestamp | null;
  first_message_content: string | null;
  first_message_id: BigIntString;
  guild_id: BigIntString;
  guild_name: string;
  in_forum: boolean;
  is_deleted: boolean;
  is_locked: boolean;
  is_valid: boolean;
  jump_url: string;
  last_active_at: Timestamp;
  reaction_count: Generated<number | null>;
  reply_count: Generated<number | null>;
  search_vector: string | null;
  tags: string | null;
  thread_id: BigIntString;
  title: string;
  title_tokenized: string | null;
  update_count: Generated<number>;
  updated_at: Timestamp | null;
  updated_jump_url: string | null;
}

export interface PostSyncEvents {
  action: string;
  created_at: Generated<Timestamp>;
  id: Generated<BigIntString>;
  last_error: string | null;
  post_id: BigIntString;
  retries: Generated<number>;
}

export interface PostTagsJunction {
  channel_id: BigIntString;
  created_at: Timestamp;
  tag_id: BigIntString;
  thread_id: BigIntString;
}

export interface Roles {
  delete_at: Timestamp | null;
  is_deleted: Generated<boolean>;
  role_emoji: string | null;
  role_icon_url: string | null;
  role_id: BigIntString;
  role_name: string;
  role_position: Generated<number>;
  role_primary_color: BigIntString | null;
  role_secondary_color: BigIntString | null;
  role_tertiary_color: BigIntString | null;
}

export interface Tags {
  channel_id: BigIntString;
  channel_name: string | null;
  guild_name: string | null;
  tag_id: BigIntString;
  tag_name: string;
  usage_count: Generated<number>;
}

export interface ThemePresets {
  created_at: Generated<Timestamp>;
  css: string;
  description: string | null;
  id: Generated<number>;
  is_active: Generated<boolean | null>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface ThemeSubmissions {
  created_at: Generated<Timestamp>;
  css: string;
  id: Generated<number>;
  reviewed_at: Timestamp | null;
  reviewer_id: BigIntString | null;
  status: Generated<string>;
  title: string;
  user_id: BigIntString;
}

export interface UserBlockedAuthors {
  added_at: Timestamp;
  blocked_author_id: BigIntString;
  user_id: BigIntString;
}

export interface UserData {
  user_avatar_url: string | null;
  user_credit_lv1: Generated<number | null>;
  user_credit_lv2: Generated<number | null>;
  user_credit_lv3: Generated<number | null>;
  user_global_name: string | null;
  user_id: BigIntString;
  user_message_count: Generated<number | null>;
  user_nickname: string | null;
  user_thread_count: Generated<number | null>;
  user_update_count: Generated<number | null>;
  user_username: string;
}

export interface UserFastSearchCommand {
  command_name: string;
  search_conditions: string | null;
  user_id: BigIntString;
}

export interface UserFavoritePosts {
  added_at: Timestamp;
  allow_push: Generated<boolean>;
  favorite_as: BigIntString;
  favorite_type_name: string;
  thread_id: BigIntString;
  user_id: BigIntString;
}

export interface UserFavoriteTypes {
  created_at: Timestamp;
  favorite_id: Generated<BigIntString>;
  post_count: Generated<number>;
  type_name: string;
  user_id: BigIntString;
}

export interface UserFollows {
  author_id: BigIntString;
  created_at: Generated<Timestamp>;
  follower_id: BigIntString;
}

export interface UserFollowTags {
  created_at: Generated<Timestamp>;
  tag_id: BigIntString;
  user_id: BigIntString;
}

export interface UserNotifications {
  author_id: BigIntString;
  created_at: Generated<Timestamp>;
  id: Generated<BigIntString>;
  is_read: Generated<boolean | null>;
  metadata: Generated<Json | null>;
  post_id: BigIntString;
  type: string;
  user_id: BigIntString;
}

export interface UserPushList {
  thread_id: BigIntString;
  updated_at: Timestamp;
  updated_jump_url: string;
  user_id: BigIntString;
}

export interface UserRoles {
  deactive_at: Timestamp | null;
  /**
   * 是否激活（软删除）
   */
  is_active: Generated<boolean>;
  role_id: BigIntString;
  /**
   * 最后更新时间
   */
  updated_at: Generated<Timestamp>;
  user_id: BigIntString;
}

export interface Users {
  created_at: Generated<Timestamp>;
  discord_id: BigIntString;
  following_feed_viewed_at: Timestamp | null;
  is_admin: Generated<boolean | null>;
  last_login: Generated<Timestamp>;
  orientations: Generated<string[] | null>;
}

export interface UserSettings {
  author_role_color_enabled: Generated<boolean | null>;
  blocked_posts: Generated<ArrayType<BigIntString> | null>;
  card_content_font_offset: Generated<number | null>;
  card_title_font_offset: Generated<number | null>;
  custom_css: string | null;
  discord_link_mode: Generated<string | null>;
  display_mode: Generated<string | null>;
  hidden_keywords: Generated<string[] | null>;
  hidden_tags: Generated<string[] | null>;
  image_load_mode: Generated<string | null>;
  pagination_style: Generated<string | null>;
  preferred_keywords: Generated<string[] | null>;
  preferred_tags: Generated<string[] | null>;
  featured_post_id: Generated<BigIntString | null>;
  theme: Generated<string | null>;
  updated_at: Generated<Timestamp>;
  user_id: BigIntString;
}

export interface UserSubareaFollows {
  added_at: Generated<Timestamp>;
  removed_at: Timestamp | null;
  status: string;
  subarea_id: BigIntString;
  user_id: BigIntString;
}

export interface UserSubscriptionsPost {
  added_at: Timestamp | null;
  thread_id: BigIntString;
  user_id: BigIntString;
}

export interface DB {
  autocreator_data: AutocreatorData;
  channels: Channels;
  db_info: DbInfo;
  message_main: MessageMain;
  post_members: PostMembers;
  post_sync_events: PostSyncEvents;
  post_tags_junction: PostTagsJunction;
  posts_main: PostsMain;
  roles: Roles;
  tags: Tags;
  theme_presets: ThemePresets;
  theme_submissions: ThemeSubmissions;
  user_blocked_authors: UserBlockedAuthors;
  user_data: UserData;
  user_fast_search_command: UserFastSearchCommand;
  user_favorite_posts: UserFavoritePosts;
  user_favorite_types: UserFavoriteTypes;
  user_follow_tags: UserFollowTags;
  user_follows: UserFollows;
  user_notifications: UserNotifications;
  user_push_list: UserPushList;
  user_roles: UserRoles;
  user_settings: UserSettings;
  user_subarea_follows: UserSubareaFollows;
  user_subscriptions_post: UserSubscriptionsPost;
  users: Users;
}
